#ifndef __CONSTANT_H
#define __CONSTANT_H

// Constants defined in the FAPI

#define PARAM_REQUEST		0x00
#define PARAM_RESPONSE		0x01
#define CONFIG_REQUEST		0x02
#define CONFIG_RESPONSE		0x03
#define START_REQUEST		0x04
#define STOP_REQUEST		0x05
#define STOP_INDICATION		0x06
#define ERROR_INDICATION	0x07
#define DL_TTI_REQUEST		0x80
#define UL_TTI_REQUEST		0x81
#define SLOT_INDICATION		0x82
#define UL_DCI_REQUEST		0x83
#define TX_DATA_REQUEST		0x84
#define RX_DATA_INDICATION	0x85
#define CRC_INDICATION		0x86
#define UCI_INDICATION		0x87
#define SRS_INDICATION		0x88
#define RACH_INDICATION		0x89

//for DL_TTI
#define MaxUE						30	//YET TO KNOW
#define MAX_FREQ_DOM_RESOURCE 		6
#define MAX_DLDCI					30		//YET TO KNOW
#define DCI_PAYLOAD_BTYE_LEN		18 //YET TO KNOW
#define MAX_PRG						30		//YET TO KNOW
#define MAX_BEAMIDX					10	//YET TO KNOW k
#define MAX_RB_BITMAP 				36
#define PDCCH_PDU_TAG				0
#define PDSCH_PDU_TAG				1
#define CSIRS_PDU_TAG				2
#define SSB_PDU_TAG					3
#define MaxPDCCH_PDU				30
#define MaxPDSCH_PDU				30
#define MaxCSIRS_PDU 				20
#define MaxSSB_PDU 					15
#define MAX_CODE_WORDS 				10 //yet to know
#define MAXUE						10
#define MAX_UElist					10
#define MAX_REG_BUNDLE              275 // Max number of REG bundle

#define BITS_EIGHT				8
#define BITS_SIXTEEN			16
#define BITS_THIRTYTWO			32

// ul_tti_constants
#define PRACH_PDU_TAG 0
#define PUSCH_PDU_TAG 1
#define PUCCH_PDU_TAG 2
#define SRS_PDU_TAG 3

#define PUSCH_DATA_PDU_TAG 1
#define PUSCH_UCI_PDU_TAG 1
#define PUSCH_PTRS_PDU_TAG 2
#define DFTS_OFDM_PDU_TAG 3

#define MaxPRACH_PDU	20
#define MaxPUSCH_PDU	20

#define MaxPUCCH_PDU	20
#define MaxSRS_PDU 20
#define MaxUE_List 20

// MAX_CEIL_NUM is set to ceil(150/8) as numCb from Table 3-47, FAPI document, is expected to be at most 150, 
// this parameter is used to determine the size of the cbPresentAndPosition array
#define MAX_CEIL_NUM	19 

#define MAX_PTRSPORT_CONF 10 //:todo


// L1 configurations Processing
#define MAX_TB_SIZE 1254000
#define MAX_CB 4000
#define Max_ORAN_sections 100

#define ADDRESS_HARQ 20
#define ADDRESS_TX_CBS 34
#define ADDRESS_TX_CBS_TB 52
#define ADDRESS_TX_CBCRC 35
#define ADDRESS_TX_LDPC 36
#define ADDRESS_TX_PUNCTURING 37
#define ADDRESS_TX_RATE_MATCH 38
#define ADDRESS_TX_BIT_INTERLEAVE 40
#define ADDRESS_TX_GOLD_SEQ 41
#define ADDRESS_TX_SCRAMBLING 42
#define ADDRESS_TX_MODULATOR 43
#define ADDRESS_TX_LAYER_MAPPER 44
#define ADDRESS_TX_UE_INTERLEAVER1 45
#define ADDRESS_TX_UE_INTERLEAVER2 46
#define ADDRESS_TX_RE_MAPPER 47
#define ADDRESS_TX_DMRS 48
#define ADDRESS_TX_CSIRS 49
#define ADDRESS_TX_PBCH 50
#define ADDRESS_TX_PDCCH 51
#define ADDRESS_TX_PDCCH_RE_MAPPER 56
#define ADDRESS_TX_PDCCH_DMRS 53
#define ADDRESS_TX_PDCCH_USER_INTERLEAVER 54
#define ADDRESS_TX_USER_INTERLEAVER_CB 55
#define ADDRESS_TX_REG_INTERLEAVER_CB 57

#define ADDRESS_RX_RE_DEMAPPER 64
#define ADDRESS_RX_DMRS 65
#define ADDRESS_RX_CH_EQ 66
#define ADDRESS_RX_UE_INTERLEAVE_WRITE 67
#define ADDRESS_RX_UE_INTERLEAVE_READ_L1 68
#define ADDRESS_RX_UE_INTERLEAVE_READ_L2 69
#define ADDRESS_RX_UE_INTERLEAVE_READ_L3 70
#define ADDRESS_RX_UE_INTERLEAVE_READ_L4 71
#define ADDRESS_RX_LAYER_MAPPER 72
#define ADDRESS_RX_LDPC 78
#define ADDRESS_RX_DEPUNCTURING 77
#define ADDRESS_RX_RATE_DEMATCH 76
#define ADDRESS_RX_DEINTERLEAVER 75
#define ADDRESS_RX_DESCRAMBLING 74
#define ADDRESS_RX_FILLER_BIT 79
#define ADDRESS_RX_LLR_GEN_BIT 73
#define ADDRESS_RX_CBCRC 80
#define ADDRESS_RX_CBS_WRITE 81
#define ADDRESS_RX_CBS_READ 82
#define ADDRESS_RX_TBCRC 83
#define ADDRESS_RX_PUCCHF0 85
#define ADDRESS_RX_PUCCHF0_INTERLEAVE_WRITE 86
#define ADDRESS_RX_PUCCHF0_INTERLEAVE_READ 87
#define ADDRESS_RX_PUCCHF2_INTERLEAVE_WRITE 88
#define ADDRESS_RX_PUCCHF2_INTERLEAVE_READ 89
#define ADDRESS_RX_PUCCHF2_DESCRAMBLER 90
#define ADDRESS_RX_PUCCHF2 91
#define ADDRESS_RX_PUCCHF2_DMRS 92
#define ADDRESS_RX_PUCCH_DEC_SHORT_LENGTH 93
#define ADDRESS_RX_PUCCH_RR_SHORT_LENGTH 94
#define ADDRESS_RX_PRACH_PDU_LENGTH 95

#define ADDRESS_RX_SRS_GRID 129
#define ADDRESS_RX_SRS_SEQ 130
#define ADDRESS_RX_SRS_FAPI_OUT 131


#define ADDRESS_ORAN_M_PLANE 96
#define ADDRESS_ORAN_C_PLANE 104
#define ADDRESS_ORAN_U_PLANE 112
#define ADDRESS_ORAN_S_PLANE 120

#define MAX_PRB_BW 273
#define MAX_ORAN_DL_LAYERS 1
#define MAX_ORAN_UL_LAYERS 1

#define ADDRESS_RX_Data_indication 128

#define ADDRESS_RACH_indication 128

#define ADDRESS_UCI_indication 128

#define MAX_CONFIG_PACKETS 16000

#endif
